### ISSUE TITLE
GPL协议要求在分发二进制的同时也要附带其源代码

### ISSUE THREAD

**Issue by iamyou** [leoweyr/OdysseyWorld#19]
https://github.com/leoweyr/OdysseyWorld/blob/52d80111d50f3fd502bfedb475ea9c16447aed91/LICENSE#L34-L38

https://github.com/leoweyr/OdysseyWorld/blob/52d80111d50f3fd502bfedb475ea9c16447aed91/SDK/package/compiled/quantumRandom.pyd

**Comment by leoweyr** [comment]
Please Notice "COPIES OF", here is the main source.

**Comment by leoweyr** [comment]
And the PACKAGE is just a showed temp, it is not included in the open source domain and will be removed later.
