### ISSUE TITLE
Pass char* to the FolderPoint and FrameLibPoint DLLEXPORT function 

### ISSUE THREAD

**Issue by leoweyr** [leoweyr/OdysseyWorld#22]
## 🚩Requirement
>In FolderPoint: DLLEXPORT BOOL filePath(LPCTSTR logicPath,std::string *concretePath)

change into
```cpp
DLLEXPORT BOOL filePath(char* logicPath,char* concretePath)
```

>In FrameLibPoint: DLLEXPORT BOOL dllPath(std::string dllName,std::string *dllPath)

change into
```cpp
DLLEXPORT BOOL dllPath(char* dllName,char* dllPath)
```
**Inorder to python use ctypes to call the dll written by cpp.**

## 💻How to debug
- Aimed Program: `FrameLibPoint.cpp` or `FolderPoint.cpp`, they both are depended on registry operation from `WindowsRegistry.h`.
- Before you are about to debug, you must run `a.exe` which is under `Setup` file folder.
- When you are debugging: Delete modifier `DLLEXPORT`, and call the dll exported function in `int main{}`. That means just try to pass in char* into the dll exported function, change the pointer value inside the function, and successfully output outside the function. For this purpose, you should coding and adapt incoming pointers to in-function code design goals.

#### For example in ForderPoint.cpp:
```cpp
#include "../WindowsRegistry/WindowsRegistry.h"

BOOL filePath(char* logicPath,char* concretePath){
    //your rewrite of the code is here
}

int main(){
    char concretePath;
    filePath("a1",&concretePath)
    std::cout << concretePath << std::endl;
    return 0;
}
//If it prints >> OdysseyWorld\character
//That means your rewrite of the code is success.
```
And then rewrite the hole code to:
```cpp
#define DLLEXPORT extern "C" __declspec(dllexport)
#include "../WindowsRegistry/WindowsRegistry.h"

DLLEXPORT BOOL filePath(char logicPath,char *concretePath){
    //your rewrite of the code is here
}
```
Pull requests finally.

#### For example in FrameLibPoint.cpp:
```cpp
#include "../WindowsRegistry/WindowsRegistry.h"

BOOL dllPath(char* dllName,char* dllPath){
    //your rewrite of the code is here
}

int main(){
    char dllFilePath;
    dllPath("FolderPoint",&dllFilePath)
    std::cout << dllFilePath << std::endl;
    return 0;
}
//If it prints >> OdysseyWorld\character\frameLib\FolderPoint.dll
//That means your rewrite of the code is success.
```
And then rewrite the hole code to:
```cpp
#define DLLEXPORT extern "C" __declspec(dllexport)
#include "../WindowsRegistry/WindowsRegistry.h"

DLLEXPORT BOOL dllPath(char* dllName,char* dllPath){
    //your rewrite of the code is here
}
```
Pull requests finally.

**Comment by leoweyr** [comment]
Before you are about to debug, you must run a.exe which is under "Setup" file folder.

**Comment by leoweyr** [comment]
When you are debugging: Delete modifier `DLLEXPORT`, and call the dll  exported function in `int main{}`. That means just try to pass in char* into the dll exported function, change the pointer value inside the function, and successfully output outside the function. For this purpose, you should coding and adapt incoming pointers to in-function code design goals.
​The `int main{}` can be in FolderPoint.cpp:
​```cpp
int main{
    char concretePath;
    filePath("a1",&concretePath)
    cout << concretePath << endl;
    return 0;
}
\\if output: OdysseyWorld\character
\\That means success
​```

**Comment by iamyou** [comment]
> And then rewrite the hole code to:

You may mean the  **whole** code

**Comment by leoweyr** [comment]
> > And then rewrite the hole code to:
> 
> You may mean the **whole** code

Sometimes I like to play puns, so do you have a solution?

**Comment by iamyou** [comment]
> > > And then rewrite the hole code to:
> > 
> > 
> > You may mean the **whole** code
> 
> Sometimes I like to play puns, so do you have a solution?

Wow,you will grow out of it

**Comment by leoweyr** [comment]
Discussions #28
